---
#olx:
  #link: 'https://webcache.googleusercontent.com/search?q=cache:Mo84ecp8oMwJ:https://www.olx.ro/oferte/q-tastatura-razer/+&cd=1&hl=en&ct=clnk&gl=ro&client=ubuntu'
  #root: '//div[@class="offer-wrapper"]/table/tbody'
  #href: 'tr/td/div/h3/a/@href'
  #title: 'tr/td/div/h3/a/strong/text()'
  #place: '(tr/td/div/p/small/span/text())[1]' 
  #date: '(tr/td/div/p/small/span/text())[2]'
  #price: 'tr/td/div/p/strong/text()'

pcgarage:
  link: 'https://webcache.googleusercontent.com/search?q=cache:Ms0bOXId9pwJ:https://www.pcgarage.ro/tastaturi-gaming/razer/+&cd=1&hl=en&ct=clnk&gl=ro&client=ubuntu'
  root: '//div[@class="product_box"]'
  href: './/h2[@class="my-0"]/a/@href'
  title: './/h2[@class="my-0"]/a/text()'
  place: '/..' 
  date: ".//div[contains(@class, 'product_box_availability')]/text()"
  price: './/p[@class="price"]/text()'
