version: '3'
services:
  my-service:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: ptsw

    volumes:
      - ..:/PTSW:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
