---
olx:
    link: "https://www.olx.ro/d/oferte/q-lumix-f1.7-25mm/?search%5Border%5D=filter_float_price:asc"
    root: '//div[@class="css-1apmciz"]'
    fields:
        title: "div/h6/text()"
        place: "div[2]/p/text()[1]"
        date: "div[2]/p/text()[3]"
        price: "div[1]/p/text()"
        relative-href: "../../../../a/@href"