[rtx3060]
link = "https://www.emag.ro/placi_video/filter/procesor-video-f9897,nvidia-geforce-rtx-3060-v-9758167/sort-priceasc/c"
root = '//div[@class="card-item card-standard js-product-data"]'
next-page = '//a[contains(@class, "js-next-page")]/@href'
threshold = 10
price-limit = 2200

[rtx3060.fields]
title = "div/div/div/div/a/text()"
stoc = "div/div/div/div/div/div/text()"
price = 'div/div/div/div/p[@class="product-new-price"]/text()'
href = "div/div/div/div/a/@href"

[procesor]
link = "https://www.emag.ro/procesoare/filter/socket-f2677,1700-v31299/sort-priceasc/c"
root = '//div[@class="card-item card-standard js-product-data"]'
threshold = 10
price-limit = 2200

[procesor.fields]
title = "div/div/div/div/a/text()"
stoc = "div/div/div/div/div/div/text()"
price = 'div/div/div/div/p[@class="product-new-price"]/text()'
href = "div/div/div/div/a/@href"