[epic]
link = "https://www.epicgames.com/site/en-US/careers/jobs?sessionInvalidated=true"
root = '//div[contains(@class, "JobsViewstyles__FilteredResults-sc-xcdagw-2")]/a'
next-page = '//a[contains(@class, "pagination-btn arrow")]/@href'

[epic.fields]
href = "@href"