name = 'epic'
link = "https://www.epicgames.com/site/en-US/careers/jobs?sessionInvalidated=true"
root = '//div[contains(@class, "JobsViewstyles__FilteredResults-sc-xcdagw-2")]/a'
next-page = '//a[contains(@class, "pagination-btn arrow")]/i[@class="icon-chevron-right"]/../@href'
type = 'job-listing'
driver = 'playwright'
keywords = ['junior', 'associate', 'graduate', 'Data']

[fields]
href = '@href'
position = './/div[contains(@class, "joblisting-title")]/span/text()'
department = './/div[contains(@class, "MuiGrid-grid-md-3-219")]/div/span/text()'
location = './/div[contains(@class, "MuiGrid-grid-md-2-218")]/div/text()'
company = './/div[contains(@class, "MuiGrid-grid-md-2-218")]/div/span/text()'
