[rtx3060-evomag]
link = 'https://www.evomag.ro/componente-pc-gaming-placi-video/filtru/model+chipset:geforce+rtx+3060,ordonare:pretcrescator'
root = '//div[@class="nice_product_item"]'
threshold = 10
price-limit = 2200

[rtx3060-evomag.fields]
title = 'div/a/@title'
stoc = 'div/div/a/span/text()'
price = 'div/div/div/span/text()'
href = 'div/a/@href'