[raspi]
link = 'https://www.optimusdigital.ro/ro/288-placi-raspberry-pi?orderby=quantity&orderway=desc&orderway=desc'
root = '//li[contains(@class, "ajax_block_product")]'
threshold = 0 
price-limit = 1500

[raspi.fields]
title = 'div/div/h5/a/text()'
stoc = 'div/div/span/span/text()'
price = 'div/div/div/span/text()'
href = 'div/div/h5/a/@href'