name = 'pcgarage'
link = 'https://www.pcgarage.ro/placi-video/filtre/chipset-seria-geforce-rtx-3000/memorie-dimensiune-memorie-12288/'
root = '//div[@class="product_box_parent col-xs-24 col-sm-12 col-md-8 col-lg-6 col-xl-4 col-xxl-3"]'
next-page = '//a[@aria-label="Pagina urmatoare"]/@href'
driver = 'playwright'
price-limit = 2500 
threshold = 0

[fields]
title = './/h2[@class="my-0"]/a/text()'
stoc = '''.//div[contains(@class, 'product_box_availability')]/text()'''
price = './/p[@class="price"]/text()'
href = './/h2[@class="my-0"]/a/@href'
